cubes:
  - name: product
    sql_table: public.product
    data_source: default

    joins: []

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: name
        sql: name
        type: string

      - name: timestamp
        sql: timestamp
        type: time

    measures:
      - name: count
        type: count

      - name: value
        sql: value
        type: sum

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
